##########################################################################
####        STEP 1: Rename videos and add aaa.csv metadata
##########################################################################

# A new folder named "metadata" is created.
# All videos are copied in metadata/ using the RENAMING RULES.
# Finally a file named aaa.csv is created.
# See below for further explanation.

# RENAMING RULES:
# In few words: game names are omitted and timestamps better sorted, e.g:.
# "ELDEN RING20240621123455.mp4" is copied as 123455-21-06-2024.mp4

# Clarification: according to the Playstation Software Rules,
# 123455 means that the video was registered at 12:34 o clock 
# (and 55 seconds), on the 21st June 2024.

# aaa.csv
# Database where, for each video, the user must choose the cuts (metadata).
# Example of file:
# video1.mp4,00:00:00,00:00:05
# video1.mp4,00:00:10,00:20:00
# video2.mp4,01:00:00,04:00:00
# Meaning:
# "video1.mp4" will be cut from second 0 to second 5,
# as well as from second 10 to minute 20.
# "video2.mp4" will be cut from hour 1 to hour 4.

# For each video a single line cutting the first second is generated by 
# default.
# After running the script, the user should manually edit the aaa.csv file
##########################################################################

#!/bin/sh
# If a metadata folder is already there, exit so to avoid overwriting
folder="metadata"
if [ -d ${folder} ]; then
    echo "Folder ${folder} already exists. Exiting."
    exit
fi

mkdir ${folder}
touch ${folder}/aaa.csv

# Save the names of all the files in the current directory
ls > all_files.list

# For each video file, rename and add three lines in the aaa.csv file
while read filename
do
	echo "[detected: ${filename}]"
    extension=${filename:${#filename}-4:4}
    # Check if we have a video file
    if [ ${extension} == ".mp4" ]; then
        echo "+ processing ${filename}"
	    # Preserve only the last 18 character of the filename:
        # they are precisely the timestamps and the ending .mp4
	    simple_name="${filename:${#filename}-18}"
        # Extract the parts containing year, month, day, time
    	anno="${simple_name:0:4}"
	    mese="${simple_name:4:2}"
	    giorno="${simple_name:6:2}"
	    ora="${simple_name:8:6}"
        # Create a new name by sorting these information a bit better
	    new_name=${ora}-${giorno}-${mese}-${anno}	

        # Copy the renamed video and empty metadata in a dedicated folder
	    cp "${filename}" ${folder}/${new_name}.mp4
	    echo "  [Renamed  ${new_name}.mp4]"
        # Create empty metadata files
        echo "${new_name}.mp4,00:00:00,00:00:01" >> ${folder}/aaa.csv
    else
        echo "- ignoring ${filename}"
    fi
done < all_files.list

# Remove the temporarely list of files
rm all_files.list
